"""Render a deterministic Markdown model card.

The output is a pure function of its inputs: given the same estimator class,
metrics, dataset metadata and model metadata, :func:`render_model_card` always
returns byte-identical Markdown. This makes cards diff-friendly and safe to
commit to version control.
"""

from __future__ import annotations

from typing import Any

from .importances import extract_importances
from .metadata import DatasetInfo, ModelInfo


def _format_number(value: Any) -> str:
    """Format a metric value stably: floats to 4 dp, ints as-is, else ``str``."""
    if isinstance(value, bool):
        return str(value)
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        # Round to 4 decimals, then strip trailing zeros while keeping at least
        # one digit after the point for readability.
        text = f"{value:.4f}"
        return text
    return str(value)


def _metrics_table(metrics: dict[str, Any]) -> list[str]:
    lines = ["| Metric | Value |", "| --- | --- |"]
    for key in sorted(metrics):
        lines.append(f"| {key} | {_format_number(metrics[key])} |")
    return lines


def _importance_table(rows: list[tuple[str, float]]) -> list[str]:
    lines = ["| Feature | Importance |", "| --- | --- |"]
    for name, score in rows:
        lines.append(f"| {name} | {score:.4f} |")
    return lines


def _bullets(items: list[str], *, empty: str) -> list[str]:
    if not items:
        return [empty]
    return [f"- {item}" for item in items]


def render_model_card(
    estimator: Any,
    metrics: dict[str, Any],
    dataset: DatasetInfo,
    model: ModelInfo,
    *,
    top_k_features: int = 10,
) -> str:
    """Build a Markdown model card.

    Args:
        estimator: A fitted scikit-learn estimator. Its class name and (when
            available) ``feature_importances_`` / ``coef_`` are read; the
            estimator is never mutated.
        metrics: Mapping of evaluation-metric name to value (e.g.
            ``{"accuracy": 0.97, "f1_macro": 0.96}``). Rendered sorted by name.
        dataset: Metadata describing the training/eval data.
        model: Human-authored context (intended use, limitations, ...).
        top_k_features: How many features to show in the importance table.

    Returns:
        A Markdown document as a single string, terminated by a newline.

    Raises:
        ValueError: If ``metrics`` is empty, or if feature importances cannot be
            aligned with ``dataset.feature_names``.
    """
    if not metrics:
        raise ValueError("metrics must contain at least one entry")

    estimator_type = type(estimator).__name__
    out: list[str] = []

    out.append(f"# Model Card: {model.name}")
    out.append("")
    out.append(f"**Version:** {model.version}")
    out.append(f"**Estimator:** `{estimator_type}`")
    if model.authors:
        out.append(f"**Authors:** {', '.join(model.authors)}")
    if model.license:
        out.append(f"**License:** {model.license}")
    out.append("")

    out.append("## Intended Use")
    out.append("")
    out.append(model.intended_use)
    out.append("")

    out.append("### Out-of-Scope Uses")
    out.append("")
    out.extend(_bullets(model.out_of_scope, empty="- None documented."))
    out.append("")

    out.append("## Training Data")
    out.append("")
    out.append(f"**Dataset:** {dataset.name}")
    out.append("")
    out.append(dataset.description)
    out.append("")
    out.append(f"- Samples: {dataset.n_samples}")
    out.append(f"- Features: {dataset.n_features}")
    if dataset.target_names:
        out.append(f"- Classes: {', '.join(dataset.target_names)}")
    if dataset.source:
        out.append(f"- Source: {dataset.source}")
    out.append("")

    out.append("## Evaluation Metrics")
    out.append("")
    out.extend(_metrics_table(metrics))
    out.append("")

    importances = extract_importances(
        estimator, dataset.feature_names, top_k=top_k_features
    )
    if importances is not None:
        out.append(f"## Top Feature Importances (up to {top_k_features})")
        out.append("")
        rows = [(fi.name, fi.score) for fi in importances]
        out.extend(_importance_table(rows))
        out.append("")

    out.append("## Limitations")
    out.append("")
    out.extend(_bullets(model.limitations, empty="- None documented."))
    out.append("")

    if model.ethical_considerations:
        out.append("## Ethical Considerations")
        out.append("")
        out.append(model.ethical_considerations)
        out.append("")

    out.append("---")
    out.append("")
    out.append(
        "_Generated by [modelcard](https://pypi.org/project/modelcard/). "
        "Card content is deterministic given identical inputs._"
    )
    out.append("")

    return "\n".join(out)
